### ISSUE TITLE
Compiling source error

### ISSUE THREAD

**Issue by emilychau** [fermi-lat/SolarSystemTools#2]
/Users/echau1/miniconda2/envs/fermibuild/conda-bld/fermitools_1559930515196/work/SolarSystemTools/build/Unknown-x86_64-64bit-gcc110/SolarSystemTools/ExposureCubeSun.h:53:15: error:
      reference member 'm_gtis' binds to a temporary object whose lifetime would be shorter than the
      lifetime of the constructed object
       m_gtis(std::vector<std::pair<double, double> >(0))
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
running gcc -v:
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.20.17)
Target: x86_64-apple-darwin18.6.0
Thread model: posix

uname -a:
Darwin gs66-glory 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

I ran into this error while compiling fermitools from source both on patch_branch and master with these system specifications.

**Comment by jasercion** [comment]
@emilychau Fix has been merged into the master branch.  Closing issue.  Please reopen if the problem persists.
